### ISSUE TITLE
Cannot ignore warnings in ST3

### ISSUE THREAD

**Issue by arusahni** [biermeester/Pylinter#29] opened 2013-09-09 01:59 UTC
When attempting to ignore in Build 3047, I get the following stacktrace:

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "/home/aru/.config/sublime-text-3/Packages/Pylinter/pylinter.py", line 208, in run
    self.add_ignore()
  File "/home/aru/.config/sublime-text-3/Packages/Pylinter/pylinter.py", line 337, in add_ignore
    edit = self.view.begin_edit()
TypeError: begin_edit() missing 2 required positional arguments: 'edit_token' and 'cmd'
```

**Comment by biermeester** [comment] 2013-09-09 20:33
I'm assuming that you are trying to set the `ignore` option in the sublime-settings file? If so, I'm unable to duplicate this error on ST3 build 3047 on Windows.

Please make sure you have the latest version of Pylinter installed. If the problem persists, please post your settings and Pylinter output. (To get the Pylinter output, set the `verbose` setting to `true`.)

**Comment by arusahni** [comment] 2013-09-09 23:33
I'm using Linux, for what it's worth, and am running the 2013.09.06 build of Pylinter.

Here's the stack trace I get when I do ctrl + alt + i:

```
 - PyLinter: Verbose is True
 - PyLinter: Pylint path /home/aru/.virtualenvs/lolologist/lib/python2.7/site-packages/pylint/lint.py found
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "/home/aru/.config/sublime-text-3/Packages/Pylinter/pylinter.py", line 208, in run
    self.add_ignore()
  File "/home/aru/.config/sublime-text-3/Packages/Pylinter/pylinter.py", line 337, in add_ignore
    edit = self.view.begin_edit()
TypeError: begin_edit() missing 2 required positional arguments: 'edit_token' and 'cmd'
```

**Comment by biermeester** [comment] 2013-09-13 17:05
I still can't reproduce the error. Can you post your Pylinter.sublime-settings file?

*Edit: scratch that, I can reproduce it.

**Comment by biermeester** [comment] 2013-09-13 17:34
It should be fixed now. Feel free to re-open if the problem isn't solved.

**Closed as completed by biermeester** 2013-09-13 17:34 UTC

**Comment by arusahni** [comment] 2013-09-13 22:40
Just tried it and was able to ignore warnings. Thanks for the fix!
